= Rapport d’avancement du groupe “3.2”
PACT groupe 3.2 (Les plus beaux)
ifdef::env-gitlab,env-browser[:outfilesuffix: .adoc]
:doctype: book
:stem: latexmath
:source-highlighter: coderay
:toc-title: Table des matières
:toc: macro
:sectnums:
:imagesdir: images


// Partie non numérotée
:sectnums!:
== « Groupe 3.2 »

=== Membres du groupe

* BERNAT Pierre
* DUMERY Corentin
* FEI Yixiao
* KOUKI Fedi
* MONIN Florent
* REBOULLET Paul

=== Tuteur

* KÜHNE Ulrich

=== Encadrant génie logiciel

* MOISSINAC Jean-Claude

== Résumé du sujet choisi en français (PAN1)

Ce projet envisage de permettre aux visiteurs d'un établissement de se répérer à l'intérieur de celui-ci.
Il s'adresse aux gestionnaires de ces établissements qui souhaitent offrir cet aisance à ses usagers.

Le projet est initialement pensé pour le thème "Notre campus du futur". En effet, une telle fonctionnalité serait un atout pour l'école et donnerait une image accueillante aux visiteurs. Nous avons ensuite pensé qu'il serait intéressant de pouvoir l'adapter à tout type d'établissement pour le rendre plus riche.

L'application doit permettre à l'administrateur de numériser un plan des bâtiments et de le convertir dans la structure de données choisie par les développeurs.
A l'aide de QR codes, les usagers indiquent leur position à l'application. En indiquant également la destination souhaitée, l'application les guide étape par étape jusqu'à leur destination.


== English Summary (PAN1)

This project allows the visitors of a building to get to their destinations without getting lost, provided that the owners of the building have already numerised its architectural plan.

The project was initially related to the topic "Our future campus". Indeed, such a functionality would be a must-have for the school and would give a welcoming image to the visitors. Then, we thought that it would be interesting to make it available for any building.

The app allows the administrator (the owner) to scan a map of the building, and to convert it to the data structure chosen by the developers.
Thanks to QR codes, users will know their location.After communicating their destination to the app, it guides them step by step to their destination.


// en PDF on ne peut pas controler la position de la toc
// Macros non supportées
ifndef::backend-pdf[]
== Table des matières
:toc-title:
toc::[]
endif::[]

// On numérote le reste des sections
:sectnums:

== Étude d’antériorité et justification de la proposition (PAN1)

include::proposition/proposition.adoc[Description de la proposition]

include::proposition/etat-de-l-art.adoc[Description de l’état de l’art]

== Scénarios d’usage (PAN1)

include::scenario/scenario.adoc[Scénarios d’usage]

== Architecture du projet (PAN1)

include::architecture/schema.adoc[Schéma d’architecture]

include::architecture/interfaces.adoc[Description des interfaces]

include::architecture/sequence.adoc[Diagramme de séquence]

include::architecture/ihm.adoc[Interface utilisateur graphique]

include::architecture/taches.adoc[Tableau détaillé des tâches]

== Organisation du projet (PAN1)

include::organisation/plannification.adoc[Diagramme de planification temporel des tâches]

include::organisation/repartition.adoc[Répartition des élèves par module]

include::organisation/plan-tests.adoc[Plans de test (PAN2+)]

include::organisation/avancement.adoc[Diagramme d’avancement des tâches (PAN2+)]

'''''

[bibliography]
== Bibliographie (PAN1+)

include::References.adoc[Bibliographie]

'''''

== Annexes

include::annexes/identite.adoc[Fiche d’identité du groupe (PAN1)]

include::annexes/modifications.adoc[Modifications (PAN2+)]

include::annexes/reunions.adoc[Comptes Rendus de réunions]

include::annexes/avancement.adoc[Avancement des modules]

include::annexes/moduleX.adoc[Avancement module X]

include::annexes/moduleY.adoc[Avancement module Y]
